### ISSUE TITLE
Quill crash on creating a new post (2 drafts created)

### ISSUE THREAD

**Issue by baddwin** [vickychijwani/quill#147]
- App version: 1.3.5 on Android 6.0

----

Hi, it's me again. After previous issue has been resolved, now, actually since the last update, I've got Quill crashes everytime I create a new post. The symptom is when I tap on floating button right below to create a new post, it crashes a few seconds later. And it creates 2 "Untitled" post drafts after I open it again.

FYI, I always submit the error logs via Google Playstore bug reporter.

**Comment by vickychijwani** [comment]
Hi @baddwin, sorry to hear about that. Did you try logging out and back in again? That will delete and re-create the local database, in case it's corrupted in any way.

Meanwhile I'm looking at the error logs you submitted via Google Play.

**Comment by vickychijwani** [comment]
If logging out and in doesn't work, can you invite me again to your blog (as an author), like last time? That would make it much easier to debug this.

It looks like the root cause of the crash is the double post creation. I can prevent the crash, but that probably won't stop 2 drafts from being created.

**Comment by baddwin** [comment]
does this have any clue? (sorry, screenshot is in indonesian)

![screenshot_20161104-144653](https://cloud.githubusercontent.com/assets/7449857/20036062/787c0488-a42e-11e6-9721-dc5dbe966696.jpg)

**Comment by vickychijwani** [comment]
Your screenshot just confirms what I originally said: the crash is occurring because of 2 drafts being created, but it doesn't tell me _why_ 2 posts are being created. For that I'll need to reproduce this issue myself. Or I could fix the crash for now, without fixing the double post creation, if you like.

**Comment by vickychijwani** [comment]
@baddwin I've pushed an app update (v1.4.0) that should prevent the crash, but it probably won't stop 2 drafts from getting created. Can you test it and report back with the results please?

**Comment by vickychijwani** [comment]
Hi @baddwin! It's been some time since I released the fix so hopefully you've got the update by now - does the app still crash for you?

**Comment by baddwin** [comment]
Hi @vickychijwani, thank you for the update. Quill is not crashed any more thanks to the update, but the double Untitled draft still occured, sometimes. Hope you'll have the update for it soon.

**Comment by vickychijwani** [comment]
Ok, good. I'm not able to reproduce the double draft bug though, so I don't know how to resolve it right now.
